### ISSUE TITLE
Typo in the gGnome tutorial

### ISSUE THREAD

**Issue by pwaltman** [mskilab/gGnome#11]
Maybe I'm misunderstanding something, but in the "" section, there is the sentence:

> The REF edges connecting a node to its right reference neighbor consist of two adjacencies: one leaving the “+” GRanges associated with the node and entering the **“+”** GRanges of its neighor...

Should that read?

> The REF edges connecting a node to its right reference neighbor consist of two adjacencies: one leaving the “+” GRanges associated with the node and entering the **“-”** GRanges of its neighor...

(where the REF adjacency leaves the "+" side of the node, enters the "-" side of its' neighbor)

Or am I misunerstanding something?

**Comment by imielinski** [comment]
Glad to see someone is scrutinizing the tutorial!

No, a REF edge indeed exits a + node  (eg a+) and enters the reference adjacent + node (eg b+).  For each such REF edge there is a (reverse complement) REF edge that leaves the b– node and enters the reference adjacent a- node.

This is the double stranded or “skew symmetric graph”  formulation of DNA structure.

Since the skew symmetric graph is just a ordinary directed graph, there are no “sides” to nodes.  Each node is a stranded GRanges (ie representing one strand of the double strand DNA molecule) and each edge is a 3-5 phoshodiester bond that connects the 3’ end of one node to the 5’ end of another node.

A REF edge thus connects the 3’ side of a “+” strand GRanges to 5’ side of a “+“ strand GRanges with a higher coordinate.  (or alternatively the 3’ side of a “–“ strand GRanges to the 5’ side of a lower coordinate i.e. “–“ strand GRanges).
